### PR TITLE
Alignment of Default Class Implementations to Interface definitions

### LINKED ISSUE #1584: Default class implementations do not fully implement interfaces
Langium version: 3.1.x
Package name: Langium

## Steps To Reproduce

1. See issue #1579 

Link to code example:
```typescript
export interface DocumentSymbolProvider {
    ...
    getSymbols(document: LangiumDocument, params: DocumentSymbolParams, cancelToken?: CancellationToken): MaybePromise<DocumentSymbol[]>;
}


export class DefaultDocumentSymbolProvider implements DocumentSymbolProvider {
    ...
    getSymbols(document: LangiumDocument): MaybePromise<DocumentSymbol[]> {
        return this.getSymbol(document, document.parseResult.value);
    }
    ...
}
```

## The current behavior
Some `DefaultXYZProvider` classes do not fully implement their corresponding interface. Due to TypeScript's structural typing, this is allowable but may prevent proper subclassing and/or overriding of default methods.

## The expected behavior
Where appropriate, `DefaultXYZ` classes should fully implement their corresponding interfaces and/or provide documentation regarding the implementation.

## Notes
image

### PR DESCRIPTION
**Pull request by snarkipus**
Resolves #1584 

### Summary:
- Added cancellation token support to various language server protocol (LSP) methods, allowing operations to be interrupted.
- Updated method signatures across multiple LSP providers (e.g. completion, definition, document highlight) with updated documentation and optional parameters.
- Implemented default no-op implementations for several DocumentUpdateHandler methods to reduce boilerplate in subclasses.
- Refactored several methods to use optional parameters with default values instead of explicitly passing default values, improving code readability.

### CODE REVIEW

File: packages/langium/src/lsp/document-update-handler.ts [hunk 1]
```diff
@@ -119,4 +142,25 @@ export class DefaultDocumentUpdateHandler implements DocumentUpdateHandler {
         this.fireDocumentUpdate(changedUris, deletedUris);
     }
 
+    didOpenDocument(_event: TextDocumentChangeEvent<TextDocument>): void {
```
Comment (spoenemann) [inline packages/langium/src/lsp/document-update-handler.ts:145]: The interface methods are optional, so there's no need to provide empty implementations here.

File: packages/langium/src/lsp/workspace-symbol-provider.ts [hunk 2]
```diff
@@ -46,11 +54,12 @@ export class DefaultWorkspaceSymbolProvider implements WorkspaceSymbolProvider {
         this.fuzzyMatcher = services.lsp.FuzzyMatcher;
     }
 
-    async getSymbols(params: WorkspaceSymbolParams, cancelToken = CancellationToken.None): Promise<WorkspaceSymbol[]> {
+    async getSymbols(params: WorkspaceSymbolParams, cancelToken?: CancellationToken): Promise<WorkspaceSymbol[]> {
+        const token = cancelToken ?? CancellationToken.None;
```
Comment (spoenemann) [inline packages/langium/src/lsp/workspace-symbol-provider.ts:58]: See also https://github.com/eclipse-langium/langium/pull/1605#discussion_r1696957672. Maybe it's a matter of taste, but I don't see this as an improvement w.r.t. readability.

My argument for keeping the original syntax: By specifying the default value as part of the method signature, it's like a part of the API and thus more transparent for those using it.

File: packages/langium/src/lsp/workspace-symbol-provider.ts [hunk 3]
```diff
@@ -76,4 +85,9 @@ export class DefaultWorkspaceSymbolProvider implements WorkspaceSymbolProvider {
             return undefined;
         }
     }
+
+    async resolveSymbol(symbol: WorkspaceSymbol, _cancelToken?: CancellationToken): Promise<WorkspaceSymbol> {
```
Comment (spoenemann) [inline packages/langium/src/lsp/workspace-symbol-provider.ts:89]: The interface method is optional, so there's no need to provide a default value here.

File: packages/langium/src/workspace/configuration.ts [hunk 4]
```diff
@@ -174,7 +174,11 @@ export class DefaultConfigurationProvider implements ConfigurationProvider {
         return `${languageId}`;
     }
 
-    get onConfigurationSectionUpdate(): Event<ConfigurationSectionUpdate> {
+    onConfigurationSectionUpdate(callback: ConfigurationSectionUpdateListener): Disposable {
+        return this.onConfigurationSectionUpdateEmitter.event(callback);
+    }
+
+    protected get onConfigurationSectionUpdateEvent(): Event<ConfigurationSectionUpdate> {
```
Comment (spoenemann) [inline packages/langium/src/workspace/configuration.ts:181]: What's the reason for splitting this in two getters?

**Review by spoenemann — COMMENTED** [review]
Thank you! Most of the changes look good to me.

However, I'm not convinced of these:

> - Implemented default no-op implementations for several DocumentUpdateHandler methods to reduce boilerplate in subclasses.
> - Refactored several methods to use optional parameters with default values instead of explicitly passing default values, improving code readability.

File: packages/langium/src/lsp/workspace-symbol-provider.ts (hunk 2 above)
Comment (spoenemann) [reply packages/langium/src/lsp/workspace-symbol-provider.ts:58]: The modified solution also introduces an additional symbol in the scope so now there's `token` and `cancelToken`. This is a potential source of error, as the difference is easy to overlook. It can be mitigated by overriding the parameter value instead of adding another const variable. But even then, it's an additional line of code that needs to be understood, so I prefer the more concise form.

File: packages/langium/src/lsp/document-update-handler.ts (hunk 1 above)
Comment (snarkipus) [reply packages/langium/src/lsp/document-update-handler.ts]: Rremoved.

File: packages/langium/src/lsp/workspace-symbol-provider.ts (hunk 2 above)
Comment (snarkipus) [reply packages/langium/src/lsp/workspace-symbol-provider.ts]: Reverted default parameters.

File: packages/langium/src/lsp/workspace-symbol-provider.ts (hunk 3 above)
Comment (snarkipus) [reply packages/langium/src/lsp/workspace-symbol-provider.ts]: Removed no-op method implementations.

File: packages/langium/src/workspace/configuration.ts (hunk 4 above)
Comment (snarkipus) [reply packages/langium/src/workspace/configuration.ts]: Semantics - reverted to original. 👍

File: packages/langium/src/lsp/document-update-handler.ts (hunk 1 above)
Comment (snarkipus) [reply packages/langium/src/lsp/document-update-handler.ts]: Removed no-op implementations.

File: packages/langium/src/lsp/document-update-handler.ts [hunk 5]
```diff
@@ -21,23 +21,46 @@ import type { MaybePromise } from '../utils/promise-utils.js';
...
 
+    /**
+     * A docuemnt save event (initiated) was triggered by the `TextDocuments` service.
+     * @param event The document change event.
+     * @returns An array of text edits which will be applied to the document before it is saved.
+     */
     willSaveDocumentWaitUntil?(event: TextDocumentWillSaveEvent<TextDocument>): MaybePromise<TextEdit[]>;
 
+    /**
+     * A docuemnt save event (completed) was triggered by the `TextDocuments` service.
```
Comment (msujew) [inline packages/langium/src/lsp/document-update-handler.ts:50]: Typo:
```suggestion
     * A document save event (completed) was triggered by the `TextDocuments` service.
```

File: packages/langium/src/lsp/document-update-handler.ts [hunk 6]
```diff
@@ -21,23 +21,46 @@ import type { MaybePromise } from '../utils/promise-utils.js';
...
+     * @param event The document change event.
+     */
     didSaveDocument?(event: TextDocumentChangeEvent<TextDocument>): void;
 
+    /**
+     * A docuemnt close event was triggered by the `TextDocuments` service.
```
Comment (msujew) [inline packages/langium/src/lsp/document-update-handler.ts:56]: Typo:
```suggestion
     * A document close event was triggered by the `TextDocuments` service.
```

File: packages/langium/src/workspace/configuration.ts [hunk 7]
```diff
@@ -174,7 +174,7 @@ export class DefaultConfigurationProvider implements ConfigurationProvider {
         return `${languageId}`;
     }
 
-    get onConfigurationSectionUpdate(): Event<ConfigurationSectionUpdate> {
+    get onConfigurationSectionUpdate():  Event<ConfigurationSectionUpdate> {
```
Comment (msujew) [inline packages/langium/src/workspace/configuration.ts:177]: Formatting:
```suggestion
    get onConfigurationSectionUpdate(): Event<ConfigurationSectionUpdate> {
```

**Review by msujew — APPROVED** [review]
Looks good to me, thanks 👍
